### ISSUE TITLE
DateTaime.IsZero() should support pointer receiver

### ISSUE THREAD

**Issue by pavel-boldyrev-form3** [go-openapi/strfmt#106]
I think this is a regression after https://github.com/go-openapi/strfmt/pull/105, particularly [this line](https://github.com/go-openapi/strfmt/pull/105/files#diff-9087329ff82d586a2f2e2393b726e00312bbd94506e54899e2012b93041bd698R133): 
```golang
func (t DateTime) IsZero() bool {
	return time.Time(t).IsZero()
}
```
I think `IsZero()` func should accept a pointer receiver, as it may be called on `nil` values.

For example, I have a generated code from a swagger model that does the following check on an optional date-time field `created_on` in the request:
```golang
func (m *Entity) validateCreatedOn(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedOn) { // not required
		return nil
	}

	if err := validate.FormatOf("created_on", "body", "date-time", m.CreatedOn.String(), formats); err != nil {
		return err
	}

	return nil
}
```
which now panics on the very first `if` statement.

**Comment by piepmatz** [comment]
Alternative: https://github.com/go-openapi/swag/pull/67
