### ISSUE TITLE
make strfmt types compatible with mgo

### ISSUE THREAD

**Issue by GlenDC** [go-openapi/strfmt#11]
Right now the types provided by this library aren't compatible with mgo, as they lack the required `SetBSON` (implementing [mgo/bson.Setter](https://godoc.org/gopkg.in/mgo.v2/bson#Setter)) and `GetBSON` (implementing  [mgo/bson.Getter](https://godoc.org/gopkg.in/mgo.v2/bson#Getter)).

Progress has been started on this with the open PR https://github.com/go-openapi/strfmt/pull/7, but has been halted since. It's definitely a good starting point and work can continue starting from the submitted patch code.

Better mgo support has been requested several times. Following issues are related to this enhancement issue:

+ https://github.com/go-swagger/go-swagger/issues/670

While we're at it, we might as well support a type for the BSON ObjectID type as proposed by @casualjim in https://github.com/go-swagger/go-swagger/issues/884.

**Comment by casualjim** [comment]
fixed by #12
