### ISSUE TITLE
Null values are not handled by UUID

### ISSUE THREAD

**Issue by fieryorc** [go-openapi/strfmt#26]
We have generated models through go-swagger and the models look like this:
```go
// Account account
// swagger:model Account
type Account struct {

	// account Id
	AccountID strfmt.UUID `json:"accountId,omitempty"`
...
}
```

When the server sends null for the UUID, it results in the UUID.UnmarshalJson() failing as it doesn't handle null value. 
```go
// UnmarshalJSON sets the UUID from JSON
func (u *UUID) UnmarshalJSON(data []byte) error {
	l := jlexer.Lexer{Data: data}   // <<<<<<<<<<<<<
	u.UnmarshalEasyJSON(&l)
	return l.Error()
}
```

I'm not sure if the bug is the generator or in the strfmt. I'm relatively new to swagger spec, so please advice how to handle this. 

We are using swagger 2.0, and it doesn't support nullable types.

**Comment by casualjim** [comment]
if you add `x-nullable: true` in the spec it will handle null values

**Comment by fieryorc** [comment]
Awesome. Thanks, that works!

**Comment by fieryorc** [comment]
Related question: 

I understand that language like Java has explicit null value for most types including string, but in Go, it is a convention to use empty values instead of null. Examples include all primitive types (int, string) don't have equivalent null value. So, for strings it is common practice to use empty values instead of null. 

Shouldn't UUID lib allow the same semantics? That is, if the source value is null or not specified in JSON, shouldn't empty UUID be assigned instead of failing?

According to UUID RFC, (https://tools.ietf.org/html/rfc4122#page-9), 
```
   The nil UUID is special form of UUID that is specified to have all
   128 bits set to zero.
```
which doesn't seem to break the null semantics if we allow null values.

The problem with specifying x-nullable is that, they all become pointers, and making handling the UUID really painful throughout the code. Even just printing them using "%#v" prints pointer values which is not very friendly.

**Comment by fredbi** [comment]
Sounds ok to me to abide by the UUID RFC.

Please mark that the Zero for each type is atm redundantly redefined in go-swagger/go-swagger/generator/format.go (yes, one day, we should refactor that as well).
