### ISSUE TITLE
Error parsing timestamps of the format "2019-04-10T00:00:00".

### ISSUE THREAD

**Issue by jeffreydwalter** [go-openapi/strfmt#53]
Hello, I'm using go-swagger to generate an API client and hit an issue (mostly a problem with the API I'm consuming).

The Swagger API is defined incorrectly, like so:
```
  "lines": [
    {
      "invoiceNbr": "string",
      "operation": "Issue",
      "freeItem": true,
      "requestedOn": "2019-04-10T22:46:51.300Z", // The timestamp returned is actually "2019-04-10T00:00:00"
      "shipOn": "2019-04-10T22:46:51.300Z", // The timestamp returned is actually "2019-04-10T00:00:00"
```
The requestedOn and shipOn fields are defined as `strfmt.DateTime`.

I'm getting the following error when it tries to unmarshal the json:

```
parsing time "2019-04-10T00:00:00" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "" as "Z07:00"
```

Adding "2006-01-02T15:04:05" to the list of `dateTimeFormats` fixes the issue.

Can we add that format to the list? If so, I'm happy to make a PR. If not, how can I deal with this issue?

**Comment by jeffreydwalter** [comment]
That date format appears to be ISO8601 compliant (as-is RFC3339). It might be worth doing something more along the lines of this https://github.com/relvacode/iso8601 (or just using their library).

**Comment by casualjim** [comment]
Yes you can send a PR which adds the format to the list

**Comment by casualjim** [comment]
I'm not in favor of using a library for this when the stdlib can solve the issue just fine

**Comment by jeffreydwalter** [comment]
@casualjim awesome, PR created.

**Comment by jeffreydwalter** [comment]
@casualjim Thanks for the quick turnaround!
