### ISSUE TITLE
Recent breaking base64 change

### ISSUE THREAD

**Issue by NathanBaulch** [go-openapi/strfmt#56]
The `strfmt.Base64` JSON marshalers were recently switched from `base64.StdEncoding` to `base64.URLEncoding` in f620df996ebca5acd40e82c7c386ed3fa99c73e8. This breaks a Go client I'm working on which consumes a third party .net service.
If this was intended then perhaps there needs to be a way to configure the preferred base64 encoder?

**Comment by fredbi** [comment]
@NathanBaulch URLEncoding has been here since inception.
What has changed in the BSON unmarshalling of Base64.

**Comment by casualjim** [comment]
I'll address it, I think it's a valid concern.
