### ISSUE TITLE
ISO8601 parsing error

### ISSUE THREAD

**Issue by vrazdalovschi** [go-openapi/strfmt#65]
Hi, I've found an error reading this DateTime:  `2020-08-07T11:05:37.000+0000`

It is valid ISO8601, but strfmt.DateTime cannot parse this string. 
The valid layout is `2006-01-02T15:04:05.999999999Z0700`
Can you add support for this ISO8601 layout? 

Error message:
`parsing time "2020-08-07T11:05:37.000+0000": extra text: :37.000+00000x02020-08-07T11:05:37.000Z
`

Related topics:
https://stackoverflow.com/a/39180230/9601186
https://stackoverflow.com/a/28159233/9601186

**Comment by casualjim** [comment]
That format is invalid, your timezone needs a colon, it will parse this: `"2020-08-07T11:05:37.000+00:00"`

https://www.ietf.org/rfc/rfc3339.html#section-5.6
