### ISSUE TITLE
Any way to specify additional formats to use when unmarshalling strfmt.DateTime values?

### ISSUE THREAD

**Issue by padamstx** [go-openapi/strfmt#70]
Hi, I have a question about the strfmt.DateTime type. 
Is there any way that I can leverage the unmarshal functionality of strfmt.DateTime while supporting one or more additional formats for date-time values?   Logically, what I'd like to do is add one or more formats to the "dateTimeFormats" list that's defined in time.go.

Failing that, is there perhaps a way that I could define my own UnmarshalJSON() function that would be used instead of the one defined in the strfmt package?

Thanks

**Comment by casualjim** [comment]
You can replace registered type in the default dictionary to a new datetime type. 
Other than that you can submit a PR that provides a hook to add more date formats  (like export the dateTimeFormats field). 

This is a very common ask.

**Comment by padamstx** [comment]
> You can replace registered type in the default dictionary to a new datetime type.

Hi @casualjim, thanks for the quick reply... Could you perhaps provide a brief example of how I might do this so that I could "override" the Unmarshal-related functions to support additional formats?   I'm not familiar with replacing types in the default dictionary.   Thanks in advance!

**Comment by casualjim** [comment]
Every one of the strfmt types registers itself into a dictionary. https://github.com/go-openapi/strfmt/blob/master/time.go#L31-L34
Simply replacing the value for the key in the dictionary replaces the serializer/deserializer provided that it implements the right set of interfaces.

IMO the right way to solve is by exporting this: https://github.com/go-openapi/strfmt/blob/master/time.go#L75

**Comment by padamstx** [comment]
@casualjim PR opened.  Let me know if anything needs to change.  Thanks for your help on this.

**Comment by padamstx** [comment]
Thanks for getting that merged in so quickly!
