### ISSUE TITLE
How to canonicalize DateTime using UTC representation

### ISSUE THREAD

**Issue by padamstx** [go-openapi/strfmt#72]
I'm using the strfmt package within the context of a set of generated Go client SDKs that support IBM Cloud services (e.g. https://github.com/IBM/platform-services-go-sdk is one such SDK).   Each of the Go SDKs has a dependency on a "go core" library (https://github.com/IBM/go-sdk-core) that provides an enabling layer to the generated code.

Within our core libraries (we have one core per language: Go, Java, Node.js, Python, etc.) we have a strategy in place whereby we try to accept (while JSON unmarshaling) various date-time formats, but we try to marshal date-time values using the UTC representation.
For example, assume we have a simple struct like this that was generated from an openapi schema:
```
type MyModel {
	// The UTC timestamp when the role was created.
	CreatedAt *strfmt.DateTime `json:"created_at,omitempty"`
}
```

if the client received an operation response that contains a date-time value like:
```
{ "created_at": "2020-11-15T06:19:00.000-06:00"}
```
We'd unmarshal that into a strfmt.DateTime value that carries with it the tz-offset information, and currently when the value is marshaled, the resulting string would be the same as the input above, but we'd like to canonicalize this to the UTC representation:
```
{ "created_at": "2020-11-15T12:19:00.000Z"}
```
We achieve this in (for example) our Java core by using an appropriate DateTimeFormatter that carries with it the "UTC" timezone info so that the resulting string representation is in UTC.

Ideally, I'd be able to set `strfmt.MarshalFormat` to an appropriate format-string to achieve this, but so far I've been unable to figure out a way to do it via the format string alone.   Perhaps I'm just not understanding time.Time formats well enough.

Failing this approach, I think I'd need to somehow override the DateTime String() and MarshalJSON() functions to adjust the DateTime value slightly to reflect UTC time then proceed with marshaling it using strfmt.MarshalFormat.   I don't know if this functionality would appeal to other users of the strfmt package, but I suppose it could be implemented natively in strfmt with some sort of option to enable it (e.g. `strfmt.MarshalAsUTC = true`, etc.).

Any advice on the best way to achieve this?
Thanks in advance for any help!

Edit: After a little more education on the "time" package, it looks like this would be as simple as calling the time.UTC() function and then formatting that using strfmt.MarshalFormat.

**Comment by fredbi** [comment]
> Edit: After a little more education on the "time" package, it looks like this would be as simple as calling the time.UTC() function and then formatting that using strfmt.MarshalFormat.

@padamstx  yes `strfmt.DateTime` is only about transforming strings to times. Timezones should be manipulated at a different level. So you got it: `time.UTC()` is your "canonicalizer".

**Comment by casualjim** [comment]
You can specify such a function now: https://github.com/go-openapi/strfmt/blob/master/time.go#L82

But this is a global thing, I think there are many use cases where you don't want to override this at a global level. Or where you'd want to do it on the way in as opposed to on the way out

**Comment by padamstx** [comment]
> You can specify such a function now: https://github.com/go-openapi/strfmt/blob/master/time.go#L82
> 
> But this is a global thing, I think there are many use cases where you don't want to override this at a global level. Or where you'd want to do it on the way in as opposed to on the way out

Excellent!  That will work perfectly.  Thanks for the quick response!
