### ISSUE TITLE
No documentation on how to convert a time.Time to strfmt.DateTime

### ISSUE THREAD

**Issue by ryanwalls** [go-openapi/strfmt#8]
I have a strfmt.DateTime field and I'm trying to set a time.Time value to it.  What is the proper way to do it?  I see a `ParseDateTime` method but seems painful to convert time.Time to a string and then parse it. 

Side note: more documentation in the README would really be nice.  Pretty bare bones right now.

**Comment by casualjim** [comment]
you should be able to do: `strfmt.DateTime(time.Now())`

**Comment by ryanwalls** [comment]
Oh yeah, see now that strfmt.DateTime is just a time.Time.  Thanks.  Would still like documentation on the repo with examples, but feel free to close.

**Comment by GlenDC** [comment]
@ryanwalls all documentation can be found under the `/docs` folder, which is per-release also generated at https://goswagger.io, we might want to update the README.md to also include info about the fact that the latest docs can always be found under the `/docs` folder.

On top of that we should perhaps add some more documentation about the strfmt functionality.

**Comment by etsangsplk** [comment]
Took me a while until I find this!
https://golang.org/ref/spec#Conversions
x's type and T have identical underlying types.
